package viewGUI;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Hashtable;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Bobby
 */
public class LoginPage extends javax.swing.JPanel {

   private Hashtable<String,String> loginHash = new Hashtable<String,String>();
   private static final int NUMBER_BUTTON_WIDTH = 250;
   private static final int PASSWORD_FIELD_WIDTH = 760;
   private static final int ENTER_AND_CLEAR_GAP = 530;
	
	/**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        loginHash.put("1111", "Welcome Robert!");
        loginHash.put("2222", "Welcome Nsama!");
        loginHash.put("3333", "Welcome Paul!");
        loginHash.put("4444", "Welcome Eric!");
        loginHash.put("5555", "Welcome Andrew!");
        loginHash.put("9999", "Welcome Guest!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    
    	imagePanel = new JPanel();
    	homeScreen = null;
    	try{
    		homeScreen = new ImageIcon("Images/Gym.PNG");
    		System.out.println("Should have created new ImageIcon");
    	}
    	catch(Exception e){
    		
    	}
    	
    	homeLabel = new JButton();
    	homeLabel.setIcon(homeScreen);
    	homeLabel.setEnabled(false);
    	imagePanel.add(homeLabel);
    	
    	jPasswordField1 = new javax.swing.JPasswordField();
       
    	button4 = new NumPadButton(jPasswordField1,"4");
        button5 = new NumPadButton(jPasswordField1,"5");
        button7 = new NumPadButton(jPasswordField1, "7");
        button8 = new NumPadButton(jPasswordField1,"8");
        button9 = new NumPadButton(jPasswordField1,"9");
        button6 = new NumPadButton(jPasswordField1, "6");
        button1 = new NumPadButton(jPasswordField1,"1");
        button2 = new NumPadButton(jPasswordField1,"2");
        button3 = new NumPadButton(jPasswordField1,"3");
        button0 = new NumPadButton(jPasswordField1,"0");
      
        buttonEnter = new JButton("Enter");
        buttonClear = new JButton("Clear");
        
        buttonEnter.addActionListener(new ActionListener(){

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				String pass = jPasswordField1.getText();
				String welcomeMessage = loginHash.get(pass);
				
				if(welcomeMessage != null){
					JOptionPane.showMessageDialog(null, welcomeMessage);
					
					
					gymInterface.refresh(imagePanel);
				}
				else{
					JOptionPane.showMessageDialog(null, "No user with that password can be found.");
					jPasswordField1.setText("");
				}
			}
        	
        });

        buttonClear.addActionListener(new ActionListener(){

			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				jPasswordField1.setText("");
			}
        	
        });
        
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, PASSWORD_FIELD_WIDTH, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(button4, javax.swing.GroupLayout.DEFAULT_SIZE, NUMBER_BUTTON_WIDTH, Short.MAX_VALUE)
                                        .addComponent(button7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, NUMBER_BUTTON_WIDTH, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, NUMBER_BUTTON_WIDTH, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(button5, javax.swing.GroupLayout.DEFAULT_SIZE, NUMBER_BUTTON_WIDTH, Short.MAX_VALUE)
                                    .addComponent(button8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(button0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(button3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, NUMBER_BUTTON_WIDTH, Short.MAX_VALUE)
                                    .addComponent(button6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(button9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(ENTER_AND_CLEAR_GAP, ENTER_AND_CLEAR_GAP, ENTER_AND_CLEAR_GAP)
                        .addComponent(buttonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, Short.MAX_VALUE)))
                .addContainerGap(1200, 1200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button1)
                    .addComponent(button2)
                    .addComponent(button3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button4)
                    .addComponent(button5)
                    .addComponent(button6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button7)
                    .addComponent(button8)
                    .addComponent(button9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button0)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>                        

    private JPanel getIconPage(){
    	return imagePanel;
    }

    // Variables declaration - do not modify                     
    private NumPadButton button3;
    private NumPadButton button0;
    private JButton buttonEnter;
    private JButton buttonClear;
    private NumPadButton button4;
    private NumPadButton button5;
    private NumPadButton button7;
    private NumPadButton button8;
    private NumPadButton button9;
    private NumPadButton button6;
    private NumPadButton button1;
    private NumPadButton button2;
    private javax.swing.JPasswordField jPasswordField1;
    private JPanel imagePanel;
    private ImageIcon homeScreen;
    private JButton homeLabel;
    // End of variables declaration    
    
    public static void main(String [] args){
    	JFrame test = new JFrame();
    	LoginPage login = new LoginPage();
    	test.add(login);
    	test.setLocationRelativeTo(null);
    	test.setMinimumSize(new Dimension(400,400));
    	test.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    	test.setVisible(true);
    	
    	JFrame test2 = new JFrame();
    	test2.add(login.getIconPage());
    	test2.setLocationRelativeTo(null);
    	test2.setMinimumSize(new Dimension(400,400));
    	test2.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    	test2.setVisible(true);
    }
}
