import java.awt.Dimension;
import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import Model.TeamModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Bobby
 */
public class BracketsPage extends javax.swing.JPanel {

    /**
     * Creates new form BracketsPage
     */
    public BracketsPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	BracketButton finalButton = null;
    	firstEightBracket = new ArrayList<BracketButton>();
    	  
        team1 = new BracketButton();
        team2 = new BracketButton(team1);
        team1.setBracketButton(team2);
       
        team3 = new BracketButton();
        team4 = new BracketButton(team3);
        team3.setBracketButton(team4);
        
        team5 = new BracketButton();
        team6 = new BracketButton(team5);
        team5.setBracketButton(team6);
        
        team7 = new BracketButton();
        team8 = new BracketButton(team7);
        team7.setBracketButton(team8);
        
        winB1 = new BracketButton(finalButton);
        team1.setNextBracketButton(winB1);
        team2.setNextBracketButton(winB1);
        
        winB2 = new BracketButton(winB1);
        team3.setNextBracketButton(winB2);
        team4.setNextBracketButton(winB2);
        winB1.setBracketButton(winB2);
        
        winB3 = new BracketButton(finalButton);
        team5.setNextBracketButton(winB3);
        team6.setNextBracketButton(winB3);
        
        winB4 = new BracketButton(winB3);
        team7.setNextBracketButton(winB4);
        team8.setNextBracketButton(winB4);
        winB3.setBracketButton(winB4);
        
        semi1 = new BracketButton(finalButton);
        winB1.setNextBracketButton(semi1);
        winB2.setNextBracketButton(semi1);
        
        
        semi2 = new BracketButton(semi1);
        winB3.setNextBracketButton(semi2);
        winB4.setNextBracketButton(semi2);
        semi1.setBracketButton(semi2);
        
      
        winner = new BracketButton(finalButton);
        semi1.setNextBracketButton(winner);
        semi2.setNextBracketButton(winner);
        
        firstEightBracket.add(team1);
        firstEightBracket.add(team2);
        firstEightBracket.add(team3);
        firstEightBracket.add(team4);
        firstEightBracket.add(team5);
        firstEightBracket.add(team6);
        firstEightBracket.add(team7);
        firstEightBracket.add(team8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(team1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(team2)
                        .addGap(18, 18, 18)
                        .addComponent(winB1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(team6)
                        .addGap(18, 18, 18)
                        .addComponent(winB3)
                        .addGap(18, 18, 18)
                        .addComponent(semi2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(team7)
                        .addGap(18, 18, 18)
                        .addComponent(winB4))
                    .addComponent(team8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(team3)
                                .addGap(18, 18, 18)
                                .addComponent(winB2)
                                .addGap(18, 18, 18)
                                .addComponent(semi1))
                            .addComponent(team4)
                            .addComponent(team5))
                        .addGap(18, 18, 18)
                        .addComponent(winner)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(team1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(team2)
                    .addComponent(winB1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(team3)
                            .addComponent(winB2)
                            .addComponent(semi1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(team4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(team5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(team6)
                            .addComponent(winB3)
                            .addComponent(semi2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(team7)
                            .addComponent(winB4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(team8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(winner)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

   
    
    
    
    
    
    public void setTeams(ArrayList<TeamModel> teams){
    	for(int i = 0; i < teams.size(); i++){
    		firstEightBracket.get(i).setTeam(teams.get(i));
    	}
    	
    	this.validate();
    	this.repaint();
    }
    
    
    // Variables declaration - do not modify 
    private ArrayList<BracketButton> firstEightBracket;
    private BracketButton team1;
    private BracketButton team2;
    private BracketButton team3;
    private BracketButton team4;
    private BracketButton team5;
    private BracketButton team6;
    private BracketButton team7;
    private BracketButton team8;
    private BracketButton winB1;
    private BracketButton winB2;
    private BracketButton winB3;
    private BracketButton winB4;
    private BracketButton semi1;
    private BracketButton semi2;
    private BracketButton winner;
    
   
    // End of variables declaration                   



    public static void main(String[] args){
    	JFrame test= new JFrame("League Bracket");
    	BracketsPage temp = new BracketsPage();
    	
    	test.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    	test.setLocationRelativeTo(null);
    	test.setMinimumSize(new Dimension(700,400));
    	test.add(temp);
    	test.setVisible(true);
    	JOptionPane.showMessageDialog(null, "About to set teams");
    	
    	ArrayList<TeamModel> teams = new ArrayList<TeamModel>();
    	
    	for(int i = 0; i < 8; i ++){
    		TeamModel tempTeam = new TeamModel("Team "+i);
    		teams.add(tempTeam);
    	}
    	
    	temp.setTeams(teams);
    }
}
